services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    profiles:
      - all
      - proxy
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ${TRAEFIK_CONFIG_FILE}:/etc/traefik/traefik.yml:ro
      - ${TRAEFIK_AUTH_DIR}:/traefik-auth:ro
    networks:
      - coder-network
      - traefik-network
      - shared-network
    depends_on:
      - socat
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://socat:2375
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    networks:
      - traefik-network
      - shared-network
    profiles:
      - all
      - proxy
    volumes:
      - ${CLOUDFLARE_CONFIG_FILE}:/etc/cloudflared/config.yml:ro
      - ${CLOUDFLARE_CREDENTIALS_DIR}:/etc/cloudflared/.cloudflared:ro
    command: tunnel --config /etc/cloudflared/config.yml run

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
