# =============================================================================# =============================================================================

# MODULE: Setup Server# Setup Server Module

# =============================================================================# =============================================================================

# DESCRIPTION:# Prepares the workspace for serving content by setting up PORT environment

#   Prepares the workspace for serving content by setting up a default web server.# variable and optionally auto-generating a default index.html file.

#   Optionally auto-generates a default index.html file for testing.

#locals {

# DEPENDENCIES:  setup_server = <<-EOT

#   - data.coder_workspace.me    export PORT="$(echo "$PORTS" | cut -d',' -f1)"

#   - data.coder_parameter.exposed_ports (from traefik-routing.tf)    cd /home/coder/workspace

#    if [ "$AUTO_GENERATE_HTML" = "true" ]; then

# PARAMETERS:      if [ ! -f index.html ] || grep -q 'auto-generated by Coder' index.html; then

#   - auto_generate_html: Whether to create a default index.html        cat <<-EOF > index.html

#   - startup_command: Optional command to run at startup<!-- auto-generated by Coder -->

#<h1>Hello from Coder</h1>

# CONFIGURATION:<p>Served on port $PORT.</p>

#   Uses the first port from exposed_ports as the default server port.<p>Access at: <a href="https://${lower(data.coder_workspace.me.name)}.weekendcodeproject.dev">https://${lower(data.coder_workspace.me.name)}.weekendcodeproject.dev</a> or <a href="http://localhost:$PORT">http://localhost:$PORT</a></p>

#EOF

# USAGE:      fi

#   # In startup script    fi

#   startup_script = join("\n", [  EOT

#     # ... other modules}

#     local.setup_server,
#   ])
#
# OUTPUTS:
#   - local.setup_server (string): Bash script segment
#
# NOTES:
#   - Creates index.html only if it doesn't exist or is auto-generated
#   - Sets PORT environment variable for use by applications
#   - Server runs in foreground (keeps workspace alive)
#
# =============================================================================

# Parameter: Auto-generate HTML
data "coder_parameter" "auto_generate_html" {
  name         = "auto_generate_html"
  display_name = "Serve Static Site"
  description  = "Toggle on to scaffold a static welcome page and run the static site server. Turn off to customize your server ports and startup command."
  type         = "bool"
  form_type    = "switch"
  default      = true
  mutable      = true
  order        = 20
}

# Parameter: Expose custom ports (only when running your own server)
data "coder_parameter" "exposed_ports" {
  count        = data.coder_parameter.auto_generate_html.value ? 0 : 1

  name         = "exposed_ports"
  display_name = "Exposed Ports"
  description  = "Add one or more ports to expose when running your own server. The first port is routed through Traefik."
  type         = "list(string)"
  form_type    = "tag-select"
  default      = jsonencode(["8080"])
  mutable      = true
  order        = 21
}

# Parameter: Startup Command
data "coder_parameter" "startup_command" {
  count        = data.coder_parameter.auto_generate_html.value ? 0 : 1
  name         = "startup_command"
  display_name = "Startup Command"
  description  = "Command to run at workspace startup (for example: npm run dev)."
  type         = "string"
  default      = ""
  mutable      = true
  order        = 22
}

# Setup server script
locals {
  setup_server = <<-EOT
    #!/bin/bash
    # Setup Server
    set -e
    
    # Export ports computed by Terraform
    export PORTS="${join(",", local.exposed_ports_list)}"
    export PORT="${element(local.exposed_ports_list, 0)}"
    
    echo "[SETUP-SERVER] Configuring workspace server..."
    echo "[SETUP-SERVER] Port: $PORT"
    
    # Navigate to workspace directory (create if it doesn't exist)
    mkdir -p /home/coder/workspace
    cd /home/coder/workspace
    
    AUTO_HTML="${data.coder_parameter.auto_generate_html.value}"

    # Auto-generate HTML if enabled
    if [ "$AUTO_HTML" = "true" ]; then
      if [ ! -f index.html ]; then
  echo "[SETUP-SERVER] Creating default index.html..."
  # Use an unquoted heredoc so shell variables like $PORT expand
  cat <<-HTML > index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coder Workspace - ${data.coder_workspace.me.name}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            line-height: 1.6;
            background: #f5f5f5;
        }
        .container {
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 { color: #333; margin-top: 0; }
        .status { 
            background: #e8f5e9;
            padding: 15px;
            border-radius: 4px;
            border-left: 4px solid #4caf50;
            margin: 20px 0;
        }
        .info {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 4px;
            border-left: 4px solid #2196f3;
            margin: 20px 0;
        }
        code {
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Monaco', 'Courier New', monospace;
        }
        a { color: #1976d2; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
    <h1>Workspace: ${data.coder_workspace.me.name}</h1>
        
    <div class="status">
      <strong>Status:</strong> Workspace is running!
    </div>
        
    <div class="info">
      <strong>Access URLs:</strong><br>
      <ul>
        <li>External: <a href="https://${lower(data.coder_workspace.me.name)}.weekendcodeproject.dev">https://${lower(data.coder_workspace.me.name)}.weekendcodeproject.dev</a></li>
      </ul>
    </div>
        
    <h2>Getting Started</h2>
        <p>This is a default page. Replace <code>index.html</code> with your own content, or start your application:</p>
        
        <pre><code># Python
python3 -m http.server $PORT

# Node.js
npx http-server -p $PORT

# Your custom app
npm start</code></pre>
        
    <h2>Workspace Info</h2>
    <ul>
      <li><strong>Owner:</strong> ${data.coder_workspace_owner.me.name}</li>
      <li><strong>Port:</strong> $PORT</li>
    </ul>
        
        <div class="footer">
            <!-- auto-generated by Coder -->
            <em>This page was auto-generated. Disable in workspace settings if not needed.</em>
        </div>
    </div>
</body>
</html>
HTML
  echo "[SETUP-SERVER] ✓ index.html created"
      else
        echo "[SETUP-SERVER] ✓ index.html already exists (leaving as-is)"
      fi
    fi
    
    # Check if custom startup command is provided
    STARTUP_CMD="${try(data.coder_parameter.startup_command[0].value, "")}" 
    if [ -n "$STARTUP_CMD" ] && [ "$STARTUP_CMD" != "" ]; then
      echo "[SETUP-SERVER] Running custom startup command..."
      echo "[SETUP-SERVER] Command: $STARTUP_CMD"
      eval "$STARTUP_CMD" &
      echo "[SETUP-SERVER] ✓ Custom command started in background"
    elif [ "$AUTO_HTML" = "true" ]; then
      # Start default Python HTTP server in background
      echo "[SETUP-SERVER] Starting default HTTP server..."
      echo "[SETUP-SERVER] Server will be available at http://localhost:$PORT"
      nohup python3 -m http.server $PORT --bind 0.0.0.0 > /tmp/http-server.log 2>&1 &
      echo $! > /tmp/http-server.pid
      sleep 2
      if ps -p $(cat /tmp/http-server.pid) > /dev/null 2>&1; then
        echo "[SETUP-SERVER] ✓ HTTP server started (PID: $(cat /tmp/http-server.pid))"
      else
        echo "[SETUP-SERVER] ⚠ HTTP server may have failed to start"
        echo "[SETUP-SERVER] Check logs: tail /tmp/http-server.log"
      fi
    else
      echo "[SETUP-SERVER] Auto HTML disabled and no startup command provided; not starting a server."
    fi
    
    echo ""
  EOT
}
