#!/bin/bash
# ==============================================================================
# Glance Dashboard Configuration Generator
# ==============================================================================
# Generates config/glance/glance.yml dynamically from the selected profiles
# stored in COMPOSE_PROFILES / SELECTED_PROFILES (or passed as arguments).
#
# Called by setup.sh:
#   - From preflight_fix_mounts() to ensure the file exists before docker up
#   - Can also be called standalone: bash tools/setup/lib/glance-generator.sh
#
# Rules:
#   - Single page only ("Home", slug: home)  — no separate External page
#   - Monitor widget entries filtered by enabled profile
#   - Small column: server-stats, speedtest (always), then profile-gated widgets
#   - Speedtest is always present (core profile)
#   - Tunnel presence drives FORCE_LINK_MODE in .env, not glance.yml URLs
#   - Navigation url: fields always use /go/<service> (link-router handles context)
#   - Internal API urls use Docker-network service names (not HOST_IP) where possible
# ==============================================================================

# Resolve SCRIPT_DIR (works whether sourced or executed directly)
_glance_gen_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_ws_root="$(cd "$_glance_gen_dir/../../.." && pwd)"

generate_glance_config() {
    local output="${1:-$_ws_root/config/glance/glance.yml}"
    local env_file="${2:-$_ws_root/.env}"

    # ── Read config from .env ────────────────────────────────────────────────
    local host_ip base_domain lab_domain kavita_port
    host_ip=$(grep "^HOST_IP=" "$env_file" 2>/dev/null | cut -d'=' -f2 | tr -d ' "') 
    host_ip="${host_ip:-192.168.2.50}"
    base_domain=$(grep "^BASE_DOMAIN=" "$env_file" 2>/dev/null | cut -d'=' -f2 | tr -d ' "')
    base_domain="${base_domain:-}"
    lab_domain=$(grep "^LAB_DOMAIN=" "$env_file" 2>/dev/null | cut -d'=' -f2 | tr -d ' "')
    lab_domain="${lab_domain:-lab}"
    kavita_port=$(grep "^KAVITA_PORT=" "$env_file" 2>/dev/null | cut -d'=' -f2 | tr -d ' "')
    kavita_port="${kavita_port:-5002}"

    # ── Determine enabled profiles ───────────────────────────────────────────
    local profiles_raw
    profiles_raw=$(grep "^COMPOSE_PROFILES=" "$env_file" 2>/dev/null | cut -d'=' -f2 | tr -d '"')
    # Also accept caller-passed profiles as $SELECTED_PROFILES env var
    if [[ -z "$profiles_raw" && -n "${SELECTED_PROFILES[*]:-}" ]]; then
        profiles_raw="${SELECTED_PROFILES[*]}"
        profiles_raw="${profiles_raw// /,}"
    fi

    _glance_has_profile() {
        local check="$1"
        [[ ",$profiles_raw," == *",$check,"* ]] || [[ ",$profiles_raw," == *",all,"* ]]
    }

    local has_networking; _glance_has_profile "networking" && has_networking=true || has_networking=false
    local has_monitoring; _glance_has_profile "monitoring" && has_monitoring=true || has_monitoring=false
    local has_ai;         _glance_has_profile "ai"         && has_ai=true         || has_ai=false
    local has_media;      _glance_has_profile "media"      && has_media=true      || has_media=false

    # ── Ensure output directory exists ───────────────────────────────────────
    mkdir -p "$(dirname "$output")"

    # ── Write config ─────────────────────────────────────────────────────────
    cat > "$output" << GLANCE_EOF
# ==============================================================================
# Glance Dashboard Configuration — AUTO-GENERATED
# ==============================================================================
# This file is generated by tools/setup/lib/glance-generator.sh.
# Re-run setup.sh or: bash tools/setup/lib/glance-generator.sh
# to regenerate it after changing service profiles.
#
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# Profiles:  ${profiles_raw:-core}
# ==============================================================================

server:
  port: 8080
  proxied: true
  allow-potentially-dangerous-html: true

branding:
  hide-footer: true
  app-name: "Weekend Stack"

pages:
  - name: Home
    slug: home
    hide-desktop-navigation: true
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: APIs & Monitoring
            sites:
              # ── Core (always present) ─────────────────────────────────────
              - title: Dozzle
                url: /go/dozzle
                check-url: http://${host_ip}:9999
                icon: si:docker
              - title: Speedtest
                url: /go/speedtest
                check-url: http://${host_ip}:8765
                icon: si:speedtest
GLANCE_EOF

    # Networking profile entries
    if $has_networking; then
        cat >> "$output" << GLANCE_EOF
              # ── Networking ────────────────────────────────────────────────
              - title: Traefik
                url: /go/traefik
                check-url: http://${host_ip}:8081/api/overview
                icon: si:traefikproxy
              - title: Pi-hole
                url: /go/pihole
                check-url: http://${host_ip}:8088/admin/
                icon: si:pihole
GLANCE_EOF
    fi

    # Monitoring profile entries
    if $has_monitoring; then
        cat >> "$output" << GLANCE_EOF
              # ── Monitoring ────────────────────────────────────────────────
              - title: Portainer
                url: /go/portainer
                check-url: http://${host_ip}:9000
                icon: si:portainer
              - title: Uptime Kuma
                url: /go/uptime-kuma
                check-url: http://${host_ip}:3001
                icon: si:uptimekuma
              - title: WUD
                url: /go/wud
                check-url: http://${host_ip}:3002
                icon: si:docker
              - title: NetData
                url: /go/netdata
                check-url: http://${host_ip}:19999
                icon: si:netdata
GLANCE_EOF
    fi

    # AI profile entries
    if $has_ai; then
        cat >> "$output" << GLANCE_EOF
              # ── AI ────────────────────────────────────────────────────────
              - title: Ollama
                url: /go/ollama
                check-url: http://${host_ip}:11434/api/tags
                icon: si:ollama
              - title: Whisper
                url: /go/whisper
                check-url: http://${host_ip}:9002
                icon: si:openai
GLANCE_EOF
    fi

    # Close monitor widget + add docker-containers widget
    cat >> "$output" << GLANCE_EOF

          - type: docker-containers
            limit: 50

      - size: small
        widgets:
          # ── Always present ─────────────────────────────────────────────
          - type: server-stats
            servers:
              - type: local
                name: Docker VM

          - type: custom-api
            title: Latest Speedtest
            cache: 5m
            url: http://speedtest-tracker:80/api/speedtest/latest
            template: |
              {{ \$data := .JSON.Get "data" }}
              {{ if \$data }}
                <div style="display: flex; justify-content: space-around; padding: 1rem 0;">
                  <div style="text-align: center;">
                    <div style="font-size: 1.6rem; font-weight: bold;" class="color-primary">{{ \$data.String "download" }}</div>
                    <div style="font-size: 0.9rem; opacity: 0.8;">↓ Mbps</div>
                  </div>
                  <div style="text-align: center;">
                    <div style="font-size: 1.6rem; font-weight: bold;" class="color-primary">{{ \$data.String "upload" }}</div>
                    <div style="font-size: 0.9rem; opacity: 0.8;">↑ Mbps</div>
                  </div>
                  <div style="text-align: center;">
                    <div style="font-size: 1.6rem; font-weight: bold;">{{ \$data.String "ping" }}</div>
                    <div style="font-size: 0.9rem; opacity: 0.8;">Ping (ms)</div>
                  </div>
                </div>
                <div style="text-align: center; font-size: 0.85rem; opacity: 0.7; margin-top: 0.5rem;">
                  Last test: {{ \$data.String "created_at" }}
                </div>
              {{ else }}
                <div style="text-align: center; padding: 1rem; opacity: 0.7;">
                  No speedtest results yet. Tests run automatically every hour.
                </div>
              {{ end }}
GLANCE_EOF

    # Media profile widgets
    if $has_media; then
        cat >> "$output" << GLANCE_EOF

          # ── Media ──────────────────────────────────────────────────────
          - type: custom-api
            cache: 5m
            title: Immich Stats
            title-url: http://${host_ip}:2283
            url: http://${host_ip}:2283/api/server-info/stats
            headers:
              x-api-key: "\${IMMICH_API_KEY}"
            template: |
              {{ \$photos := .JSON.Int "photos" }}
              {{ \$videos := .JSON.Int "videos" }}
              <div style="display: flex; justify-content: space-around; margin: 1rem 0;">
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$photos }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Photos</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$videos }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Videos</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ add \$photos \$videos }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Total</div>
                </div>
              </div>

          - type: custom-api
            cache: 5m
            title: Kavita Latest
            title-url: http://${host_ip}:${kavita_port}
            method: POST
            url: http://${host_ip}:${kavita_port}/api/Series/v2?pageNumber=1&pageSize=5
            headers:
              Authorization: "Bearer \${KAVITA_API_KEY}"
              Content-Type: application/json
            body: '{"statements":[],"combination":1,"sortOptions":{"sortField":5,"isAscending":false}}'
            template: |
              {{ range .JSON.Array "content" }}
                <li>
                  <div class="size-h4">{{ .String "name" }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">{{ .String "libraryName" }}</div>
                </li>
              {{ end }}

          - type: custom-api
            cache: 5m
            title: Navidrome Stats
            title-url: http://${host_ip}:4533
            url: http://${host_ip}:4533/rest/getUser.view?u=admin&p=admin&v=1.16.1&c=glance&f=json
            template: |
              {{ \$artists := .JSON.Int "subsonic-response.user.artistCount" }}
              {{ \$albums := .JSON.Int "subsonic-response.user.albumCount" }}
              {{ \$songs := .JSON.Int "subsonic-response.user.trackCount" }}
              <div style="display: flex; justify-content: space-around; margin: 1rem 0;">
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$artists }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Artists</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$albums }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Albums</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$songs }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Songs</div>
                </div>
              </div>
GLANCE_EOF
    fi

    # Monitoring profile: WUD widget (monitoring tools management)
    if $has_monitoring; then
        cat >> "$output" << GLANCE_EOF

          # ── Monitoring ─────────────────────────────────────────────────
          - type: custom-api
            title: What's Up Docker?
            title-url: http://${host_ip}:3002
            cache: 1h
            url: http://wud:3000/api/containers/
            method: GET
            template: |
              {{/* WUD Monitor */}}
              {{ \$containers := .JSON.Array "" }}
              {{ \$total := len \$containers }}
              {{ \$updates := 0 }}
              {{ \$running := 0 }}
              {{ \$hasUpdates := false }}

              {{ range \$containers }}
                {{ if .Bool "updateAvailable" }}
                  {{ \$updates = add \$updates 1 }}
                {{ end }}
                {{ if eq (.String "status") "running" }}
                  {{ \$running = add \$running 1 }}
                {{ end }}
              {{ end }}

              <div style="display: flex; justify-content: space-around; margin: 1rem 0;">
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$updates }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Updates</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$total }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Total</div>
                </div>
                <div style="text-align: center;">
                  <div style="font-size: 1.4rem;">{{ \$running }}</div>
                  <div style="font-size: 0.9rem; opacity: 0.8;">Running</div>
                </div>
              </div>

              <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
                {{ range \$containers }}
                  {{ if .Bool "updateAvailable" }}
                    {{ \$hasUpdates = true }}
                    <li>
                      <div class="size-h4">
                        {{ if eq (.String "status") "running" }}
                          <span class="color-positive">●</span>
                        {{ else }}
                          <span class="color-negative">●</span>
                        {{ end }}
                        <a href="http://${host_ip}:3002" target="_blank" style="color: inherit; text-decoration: none;">{{ .String "name" }}</a>
                      </div>
                      <div style="display: flex; gap: 1rem; margin-top: 0.25rem; font-size: 0.9rem; opacity: 0.8;">
                        {{ \$localValue := .String "updateKind.localValue" }}
                        {{ if ge (len \$localValue) 7 }}
                          {{ \$isSha256 := eq (slice \$localValue 0 7) "sha256:" }}
                          {{ if \$isSha256 }}
                            <span>{{ slice \$localValue 7 11 }}</span>
                          {{ else }}
                            <span>{{ \$localValue }}</span>
                          {{ end }}
                        {{ else }}
                          <span>{{ \$localValue }}</span>
                        {{ end }}
                        <div>→
                          {{ \$tagValue := .String "updateKind.remoteValue" }}
                          {{ if ge (len \$tagValue) 7 }}
                            {{ \$isSha256 := eq (slice \$tagValue 0 7) "sha256:" }}
                            {{ if \$isSha256 }}
                              <span class="color-primary">{{ slice \$tagValue 7 11 }}</span>
                            {{ else }}
                              <span class="color-primary">{{ \$tagValue }}</span>
                            {{ end }}
                          {{ else }}
                            <span class="color-primary">{{ \$tagValue }}</span>
                          {{ end }}
                        </div>
                      </div>
                    </li>
                  {{ end }}
                {{ end }}

                {{ if not \$hasUpdates }}
                  <li class="flex items-center justify-center">
                    <span class="color-positive size-h4">All containers are up to date!</span>
                  </li>
                {{ end }}
              </ul>
GLANCE_EOF
    fi

    # Close the YAML document
    echo "" >> "$output"

    if type log_success &>/dev/null; then
        log_success "Glance config generated: $output (profiles: ${profiles_raw:-core})"
    else
        echo "✓ Glance config generated: $output (profiles: ${profiles_raw:-core})"
    fi
}

# ── Standalone execution ──────────────────────────────────────────────────────
# If this script is run directly (not sourced), call generate_glance_config
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Simple logging fallback when common.sh is not loaded
    if ! type log_success &>/dev/null; then
        log_success() { echo "✓ $*"; }
        log_info()    { echo "i $*"; }
    fi
    generate_glance_config "$@"
fi
