# =============================================================================
# Coder Agent - Minimal Configuration
# =============================================================================
# This creates the Coder agent that runs inside the workspace container.

# Collect custom metadata blocks from modules
# This local is referenced by the overlaid metadata-params.tf
# NOTE: Only include ALWAYS-LOADED modules (no count conditional) to prevent evaluation loops
# Conditional modules (git_integration, github_cli, etc.) cannot be safely referenced here
# as they create circular dependencies during parameter preview evaluation
locals {
  # Only include modules that are always loaded (count = 1 or no count)
  # SSH module is always loaded, just conditionally executes
  # Git modules are conditional (count based on parameter) so excluded to prevent flickering
  all_custom_metadata = []  # Empty for now - only use built-in metadata picker options
}

module "agent" {
  source = "git::https://github.com/weekend-code-project/weekendstack.git//config/coder/template-modules/modules/coder-agent-module?ref=PLACEHOLDER"
  
  # Required architecture info
  arch = data.coder_provisioner.me.arch
  os   = "linux"
  
  # Git identity (using workspace owner info)
  git_author_name  = data.coder_workspace_owner.me.name
  git_author_email = data.coder_workspace_owner.me.email
  
  # Access URL for agent connection
  # Use host.docker.internal to ensure the agent can reach Coder via the Docker gateway
  # regardless of host firewall settings or IP changes.
  coder_access_url = "http://host.docker.internal:7080"
  
  # No additional environment variables
  env_vars = {}
  
  # Metadata blocks from metadata module (Issue #27)
  # Now includes custom blocks dynamically contributed by loaded modules
  metadata_blocks = module.metadata.metadata_blocks
  
  # Minimal startup script - just bash basics
  startup_script = join("\n", [
    "#!/bin/bash",
    "echo '[WORKSPACE] Starting workspace ${data.coder_workspace.me.name} (v103)'",
    "",
    "# Phase 1 Module: init-shell (Issue #23)",
    module.init_shell.setup_script,
    "",
    "echo '[DEBUG] Phase 1 complete. Starting Phase 2...'",
    "set +e",
    "",
    "# Phase 2 Module: node-tooling",
    module.node_tooling.tooling_install_script,
    "",
    "echo '[DEBUG] Phase 2 complete.'",
    "",
    "# Git Module: git-identity (always runs)",
    module.git_identity.setup_script,
    "",
    "# Git Module: git-integration (conditional clone based on parameter)",
    data.coder_parameter.github_repo.value != "" ? module.git_integration.clone_script : "echo '[GIT] No repository URL provided - skipping clone'",
    "",
    "# Git Module: GitHub CLI (conditional based on toggle)",
    data.coder_parameter.install_github_cli.value ? module.github_cli.install_script : "echo '[GIT] GitHub CLI installation disabled'",
    "",
    "# Git Module: Gitea CLI (conditional based on auto-detection)",
    local.use_gitea_cli ? module.gitea_cli.install_script : "echo '[GIT] Gitea CLI not needed for this repository'",
    "",
    "# Traefik Auth Setup (only runs when password is provided)",
    local.traefik_auth_setup_script,
    "",
    "# Phase 2b Module: node-modules-persistence (AFTER git clone so package.json exists)",
    module.node_modules_persistence.init_script,
    "echo '[DEBUG] Node modules complete'",
    "",
    "# Scaffold new Vite project if no git repo was cloned",
    "cd /home/coder/workspace",
    "if [ ! -f package.json ]; then",
    "  echo '[VITE] No package.json found - scaffolding new Vite + React + TypeScript project...'",
    "  export NVM_DIR=$HOME/.nvm",
    "  [ -s $NVM_DIR/nvm.sh ] && . $NVM_DIR/nvm.sh",
    "  nvm use default >/dev/null 2>&1",
    "  PKG_MGR=\"${data.coder_parameter.node_package_manager.value}\"",
    "  case \"$PKG_MGR\" in",
    "    pnpm)",
    "      CREATE_CMD='pnpm create vite@latest . -- --template react-ts --force'",
    "      INSTALL_CMD='pnpm install'",
    "      RUN_HINT='pnpm run dev'",
    "      ;;",
    "    yarn)",
    "      CREATE_CMD='yarn create vite@latest . --template react-ts --force'",
    "      INSTALL_CMD='yarn install'",
    "      RUN_HINT='yarn dev'",
    "      ;;",
    "    *)",
    "      CREATE_CMD='npm create vite@latest . -- --template react-ts --force'",
    "      INSTALL_CMD='npm install'",
    "      RUN_HINT='npm run dev'",
    "      ;;",
    "  esac",
    "  eval $CREATE_CMD",
    "  if [ $? -eq 0 ] && [ -f package.json ]; then",
    "    eval $INSTALL_CMD",
    "    echo '[VITE] ✓ New Vite project created and dependencies installed'",
    "  else",
    "    echo '[VITE] ✗ Scaffolding failed - creating minimal package.json'",
    "    echo '[VITE] ✗ Scaffolding failed - creating minimal package.json'",
    "    cat > package.json << 'PKG_EOF'",
    "{",
    "  \"name\": \"vite-workspace\",",
    "  \"private\": true,",
    "  \"version\": \"0.0.0\",",
    "  \"type\": \"module\",",
    "  \"scripts\": {",
    "    \"dev\": \"vite\",",
    "    \"build\": \"vite build\",",
    "    \"preview\": \"vite preview\"",
    "  },",
    "  \"dependencies\": {",
    "    \"react\": \"^18.3.1\",",
    "    \"react-dom\": \"^18.3.1\"",
    "  },",
    "  \"devDependencies\": {",
    "    \"@vitejs/plugin-react\": \"^4.3.4\",",
    "    \"vite\": \"^5.4.19\"",
    "  }",
    "}",
    "PKG_EOF",
    "    npm install",
    "    mkdir -p src",
    "    cat > src/main.jsx << 'MAIN_EOF'",
    "import React from 'react'",
    "import ReactDOM from 'react-dom/client'",
    "import './App.css'",
    "",
    "function App() {",
    "  return (",
    "    <div className=\"container\">",
    "      <h1>${data.coder_workspace.me.name}</h1>",
    "      <div className=\"status\">✅ Vite + React Running</div>",
    "      <div className=\"access\">",
    "        <div style={{marginBottom: '10px'}}>Access your app at:</div>",
    "        <div className=\"url\">https://${lower(data.coder_workspace.me.name)}.${var.base_domain}</div>",
    "      </div>",
    "      <h3>Quick Start</h3>",
    "      <pre><code>${data.coder_parameter.node_package_manager.value} run dev    # Start dev server{\"\\n\"}${data.coder_parameter.node_package_manager.value} run build  # Build for production</code></pre>",
    "      <p style={{fontSize: '0.9em', color: '#666', marginTop: '20px'}}>",
    "        💡 Edit <code>src/main.jsx</code> to start building your React app",
    "      </p>",
    "      <div className=\"footer\">Auto-generated by Coder Vite Template</div>",
    "    </div>",
    "  )",
    "}",
    "",
    "ReactDOM.createRoot(document.getElementById('root')).render(",
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>,",
    ")",
    "MAIN_EOF",
    "    cat > src/App.css << 'CSS_EOF'",
    "body {",
    "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;",
    "  max-width: 600px;",
    "  margin: 80px auto;",
    "  padding: 20px;",
    "  line-height: 1.6;",
    "  background: #f5f5f5;",
    "}",
    ".container {",
    "  background: white;",
    "  padding: 40px;",
    "  border-radius: 8px;",
    "  box-shadow: 0 2px 4px rgba(0,0,0,0.1);",
    "  text-align: center;",
    "}",
    "h1 { ",
    "  color: #333;",
    "  margin-top: 0;",
    "  font-size: 2em;",
    "}",
    ".status { ",
    "  background: #e8f5e9;",
    "  padding: 20px;",
    "  border-radius: 4px;",
    "  margin: 30px 0;",
    "  font-size: 1.1em;",
    "}",
    ".access {",
    "  background: #e3f2fd;",
    "  padding: 20px;",
    "  border-radius: 4px;",
    "  margin: 20px 0;",
    "}",
    ".url {",
    "  font-size: 1.2em;",
    "  color: #1976d2;",
    "  font-weight: bold;",
    "  word-break: break-all;",
    "}",
    "code {",
    "  background: #f5f5f5;",
    "  padding: 2px 8px;",
    "  border-radius: 3px;",
    "  font-family: 'Monaco', 'Courier New', monospace;",
    "}",
    "pre {",
    "  background: #f5f5f5;",
    "  padding: 15px;",
    "  border-radius: 4px;",
    "  overflow-x: auto;",
    "  text-align: left;",
    "}",
    ".footer {",
    "  margin-top: 40px;",
    "  padding-top: 20px;",
    "  border-top: 1px solid #eee;",
    "  color: #999;",
    "  font-size: 0.85em;",
    "}",
    "CSS_EOF",
    "    cat > index.html << 'HTML_EOF'",
    "<!doctype html>",
    "<html lang=\"en\">",
    "  <head>",
    "    <meta charset=\"UTF-8\" />",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
    "    <title>Vite Workspace</title>",
    "  </head>",
    "  <body>",
    "    <div id=\"root\"></div>",
    "    <script type=\"module\" src=\"/src/main.jsx\"></script>",
    "  </body>",
    "</html>",
    "HTML_EOF",
    "    cat > vite.config.js << 'VITE_BASE_EOF'",
    "import { defineConfig } from 'vite'",
    "import react from '@vitejs/plugin-react'",
    "",
    "export default defineConfig({",
    "  plugins: [react()],",
    "})",
    "VITE_BASE_EOF",
    "    echo '[VITE] ✓ Created minimal Vite project'",
    "  fi",
    "else",
    "  echo '[VITE] Using existing project from repository'",
    "fi",
    "",
    "# Phase 3 Module: docker - DISABLED for Vite template",
    "echo '[DOCKER] Disabled for Vite template'",
    "echo '[DEBUG] Docker phase complete'",
    "",
    "# Phase 5 Module: ssh (always loaded, runs conditionally based on toggle)",
    try(module.ssh.ssh_copy_script, ""),
    try(module.ssh.ssh_setup_script, ""),
    "echo '[DEBUG] SSH phase complete'",
    "",
    "",
    "# Apply allowedHosts/HMR patch to existing Vite config (in-place)",
    "cd /home/coder/workspace",
    "WORKSPACE_DOMAIN=${lower(data.coder_workspace.me.name)}.${var.base_domain}",
    "CODER_HOST=coder.${var.base_domain}",
    "PATCH_ALLOWED_HOSTS=${tostring(data.coder_parameter.patch_allowed_hosts.value)}",
    "USE_CUSTOM_COMMAND=${tostring(data.coder_parameter.use_custom_command.value)}",
    "CUSTOM_COMMAND=\"${trimspace(data.coder_parameter.startup_command.value)}\"",
    "DEFAULT_COMMAND='npx vite --host 0.0.0.0 --port 8080'",
    "RUN_COMMAND=$DEFAULT_COMMAND",
    "if [ \"$USE_CUSTOM_COMMAND\" = \"true\" ] && [ -n \"$CUSTOM_COMMAND\" ]; then",
    "  RUN_COMMAND=$CUSTOM_COMMAND",
    "fi",
    "",
    "if [ \"$PATCH_ALLOWED_HOSTS\" = \"true\" ]; then",
    "  VITE_CONFIG=\"\"",
    "  for candidate in vite.config.ts vite.config.js vite.config.mts vite.config.cjs; do",
    "    if [ -f \"$candidate\" ]; then",
    "      VITE_CONFIG=$candidate",
    "      break",
    "    fi",
    "  done",
    "  if [ -n \"$VITE_CONFIG\" ]; then",
    "    echo \"[VITE] Patching $VITE_CONFIG for allowedHosts/HMR (domain: $WORKSPACE_DOMAIN)...\"",
    "    ",
    "    # Merge allowedHosts to include workspace domain and Coder host",
    "    # If allowedHosts exists, append coder host if missing; otherwise create allowedHosts with both entries.",
    "    if grep -q 'allowedHosts' \"$VITE_CONFIG\" 2>/dev/null; then",
    "      # If coder host not present, append it into the existing array (simple inline edit)",
    "      if ! grep -q \"$CODER_HOST\" \"$VITE_CONFIG\" 2>/dev/null; then",
    "        sed -i -E \"s|(allowedHosts:\\s*\\[)([^\\]]*)(\\])|\\1\\2, \\\"$CODER_HOST\\\"\\3|\" \"$VITE_CONFIG\" || true",
    "      fi",
    "    else",
    "      sed -i \"/server:\\s*{/a\\    // CODER_PATCH_ALLOWED_HOSTS\\n    allowedHosts: [\\\"$WORKSPACE_DOMAIN\\\", \\\"$CODER_HOST\\\"],\" \"$VITE_CONFIG\"",
    "    fi",
    "    ",
    "    # Add HMR block if missing",
    "    if ! grep -q 'hmr:' \"$VITE_CONFIG\" 2>/dev/null; then",
    "      sed -i \"/server:\\s*{/,/^\\s*}/ {/^\\s*}/i\\    hmr: { host: \\\"$WORKSPACE_DOMAIN\\\", clientPort: 443 },\" \"$VITE_CONFIG\"",
    "    fi",
    "    echo \"[VITE] ✓ Patched successfully\"",
    "  else",
    "    echo \"[VITE] Skipping patch - no vite.config found\"",
    "  fi",
    "fi",
    "",
    "# Start Vite dev server with patched (or original) config",
    "export PORT=8080",
    "export NVM_DIR=\"$HOME/.nvm\"",
    "[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\"",
    "nvm use default >/dev/null 2>&1",
    "echo \"[VITE] Starting: $RUN_COMMAND\"",
    "exec bash -lc \"$RUN_COMMAND\"",
    "",
    "echo '[WORKSPACE] Workspace ready!'"
  ])
}
