#!/usr/bin/env bash
# ============================================================================
# generate-custom-profile.sh - Generate custom docker-compose profile
# ============================================================================
# This script creates a docker-compose.custom.yml file that automatically
# includes all services from selected profiles, allowing users to run
# `docker-compose up` without specifying --profile flags.
#
# Usage:
#   ./tools/env/scripts/generate-custom-profile.sh --profiles "core,ai,productivity"
#
# Output:
#   docker-compose.custom.yml - Custom profile configuration
#
# ============================================================================

set -euo pipefail

# Script directory and paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
MAPPINGS_DIR="${REPO_ROOT}/tools/env/mappings"
OUTPUT_FILE="${REPO_ROOT}/docker-compose.custom.yml"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PROFILES=""

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" >&2
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" >&2
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Show usage
show_usage() {
    cat << EOF
Usage: $0 --profiles "profile1,profile2,..."

Generate custom docker-compose profile for selected services

Options:
  --profiles   Comma-separated list of profiles (required)
  --help       Show this help message

Examples:
  # Generate custom profile for core services
  $0 --profiles "core"
  
  # Generate for multiple profiles
  $0 --profiles "core,ai,productivity"

EOF
    exit 0
}

# Parse arguments
parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --profiles)
                PROFILES="$2"
                shift 2
                ;;
            --help|-h)
                show_usage
                ;;
            *)
                log_error "Unknown option: $1"
                show_usage
                ;;
        esac
    done
    
    if [[ -z "$PROFILES" ]]; then
        log_error "Missing required --profiles argument"
        show_usage
    fi
}

# Validate prerequisites
validate_prerequisites() {
    if [[ ! -f "${MAPPINGS_DIR}/profile-to-services.json" ]]; then
        log_error "Profile mapping not found: ${MAPPINGS_DIR}/profile-to-services.json"
        exit 1
    fi
    
    if ! command -v jq &> /dev/null; then
        log_error "jq is required but not installed. Install with: sudo apt install jq"
        exit 1
    fi
}

# Get list of services for selected profiles
get_services_for_profiles() {
    local profiles_array=(${PROFILES//,/ })
    local all_services=()
    
    # Check if 'all' profile is selected
    for profile in "${profiles_array[@]}"; do
        if [[ "$profile" == "all" ]]; then
            # Return all services from all profiles
            jq -r '.[] | .[]' "${MAPPINGS_DIR}/profile-to-services.json" | sort -u
            return 0
        fi
    done
    
    # Collect services for each selected profile
    for profile in "${profiles_array[@]}"; do
        local services=$(jq -r --arg profile "$profile" '.[$profile] // [] | .[]' "${MAPPINGS_DIR}/profile-to-services.json")
        if [[ -n "$services" ]]; then
            all_services+=($services)
        else
            log_warn "Profile not found or empty: $profile"
        fi
    done
    
    # Remove duplicates and sort
    printf '%s\n' "${all_services[@]}" | sort -u
}

# Generate custom profile file
generate_custom_profile() {
    local services=($(get_services_for_profiles))
    local services_count=${#services[@]}
    
    if [[ $services_count -eq 0 ]]; then
        log_error "No services found for profiles: $PROFILES"
        exit 1
    fi
    
    log_info "Generating custom profile for $services_count services"
    
    # Generate header
    cat > "$OUTPUT_FILE" << EOF
# ============================================================================
# WEEKENDSTACK - CUSTOM PROFILE
# ============================================================================
# Auto-generated custom profile for selected services
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Selected Profiles: $PROFILES
# Services Included: $services_count services
#
# This file adds a 'custom' profile to all enabled services so you can run:
#   docker-compose up
#
# Instead of:
#   docker-compose --profile core --profile ai up
#
# ============================================================================
#
# DO NOT EDIT THIS FILE MANUALLY
# Re-run setup.sh to update this file when changing profiles
# ============================================================================

services:
EOF
    
    # Add each service with custom profile
    for service in "${services[@]}"; do
        # Skip if service name contains special characters not valid for YAML
        if [[ ! "$service" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            log_warn "Skipping invalid service name: $service"
            continue
        fi
        
        cat >> "$OUTPUT_FILE" << EOF
  ${service}:
    profiles:
      - custom

EOF
        log_info "  ✓ Added: $service"
    done
    
    # Add cloudflare-tunnel if tunnel is enabled, token is configured,
    # AND it wasn't already included via the networking profile mapping
    local env_file="${REPO_ROOT}/.env"
    if [[ -f "$env_file" ]]; then
        local cf_enabled cf_token
        cf_enabled=$(grep "^CLOUDFLARE_TUNNEL_ENABLED=true" "$env_file" 2>/dev/null || true)
        cf_token=$(grep "^CLOUDFLARE_TUNNEL_TOKEN=" "$env_file" 2>/dev/null | cut -d'=' -f2- | tr -d ' ')
        if [[ -n "$cf_enabled" && -n "$cf_token" ]]; then
            # Only append if not already in the services list (e.g. from networking profile)
            if ! printf '%s\n' "${services[@]}" | grep -qx "cloudflare-tunnel"; then
                cat >> "$OUTPUT_FILE" << EOF
  cloudflare-tunnel:
    profiles:
      - custom

EOF
                log_info "  ✓ Added: cloudflare-tunnel (tunnel enabled with token)"
                services_count=$((services_count + 1))
            fi
        fi
    fi
    
    log_success "Custom profile generated: $OUTPUT_FILE"
}

# Main execution
main() {
    parse_arguments "$@"
    validate_prerequisites
    generate_custom_profile
    
    echo ""
    echo "Custom profile created successfully!"
    echo ""
    echo "To use the custom profile:"
    echo "  1. Ensure COMPOSE_PROFILES=custom in your .env file"
    echo "  2. Run: docker-compose up -d"
    echo ""
    echo "No need to specify --profile flags!"
    echo ""
}

main "$@"
